import type { AppProps } from "next/app";
import Header from '@/components/Header'
import '../styles/globals.css'
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <main className={inter.className}>
        <Header />
        <Component {...pageProps} />
      </main>
    </>
  );
}
